User.create(username: 'marcos', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'joao', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'camila', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'afonso', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'mateus', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'junior', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'leila', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")
User.create(username: 'carlos', password: 'password123', avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg")